### PR TITLE
Fix display periods in the highlighted single value container

### LINKED ISSUE #219: [BUG] Highlighted Single Value visualizations do not display the reporting period as subtitle
## Bug Description

The **Highlighted Single Value** visualization does not display the reporting period subtitle when viewed in the **FlexiPortal**. This makes it unclear which time period the displayed value represents, which is critical for accurate interpretation of the data.

## Steps to Reproduce

1. Open the **Manager App**.
2. Configure a **Highlighted Single Value** visualization and configure it with:
3. Save the visualization and assign it to a section visible in the **FlexiPortal**.
4. Open the **FlexiPortal** and navigate to the section containing the **Highlighted Single Value**.
5. Observe the visualization.

## Expected Behavior

The **Highlighted Single Value** container should display a subtitle beneath the title that shows the configured reporting period (e.g., "2025").

## Actual Behavior

When viewed in **FlexiPortal**, the **Highlighted Single Value** container the subtitle showing the reporting period is missing.

## Environment

- OS: Linux (Ubuntu 22.04)
- Browser: Chrome
- Device: Desktop

### PR DESCRIPTION
**Pull request by tibendadavis**
This PR add a subtitle to the Highlighted Single Value Visualizer Container which shows the periods for the data being shown

Fixes #219

### CODE REVIEW

**Comment by nnkogift** [comment]
This doesn't work for relative periods. Please fix it for relative periods as well

**Comment by tibendadavis** [comment]
Using the filters prop from the visualization config, it now works for both relative and fixed periods.  Kindly re-review @nnkogift

File: apps/portal/src/components/displayItems/HighlightedSingleValueVisualizer/components/HighlightedSingleValueContainer.tsx [hunk 1]
```diff
@@ -20,15 +23,22 @@ export async function HighlightedSingleValueContainer({
 	} as ChartVisualizationItem);
 
 	const imageURL = getServerImageUrl(config.icon);
-
-	const periods = visualizationConfig.periods ?? [];
+	const periodIds =
+		find(visualizationConfig.filters, {
+			dimension: DefaultAnalyticsDimension.pe,
+		})?.items?.map((item) => item.id) ?? [];
```
Comment (nnkogift) [inline apps/portal/src/components/displayItems/HighlightedSingleValueVisualizer/components/HighlightedSingleValueContainer.tsx:29]: You can directly map from the ids to the period objects here instead of using a for loop after this

**Review by nnkogift — CHANGES_REQUESTED** [review]

File: apps/portal/src/components/displayItems/HighlightedSingleValueVisualizer/components/HighlightedSingleValueContainer.tsx (hunk 1 above)
Comment (tibendadavis) [reply apps/portal/src/components/displayItems/HighlightedSingleValueVisualizer/components/HighlightedSingleValueContainer.tsx]: done!
